[package]
name = "Closed_Ecosphere"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0-rc.3"
rand = "0.8.5"
bevy_dev_tools = "0.15.0-rc.3"
kdtree = "0.7.0"
num-traits = "0.2.19"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
